language: ruby
script: bundle exec rake test
rvm:
  - 1.8.7
  - 1.9.3
  - 2.6.10
  - 2.7.8
  - 3.0.0
  - 3.1.0
  - 3.2.0
  
gemfile:
  - gemfiles/2.3.gemfile
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/4.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/2.3.gemfile
